spring.application.name=Tickets
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:5506/ticketsdb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

logging.file.name=Evento/logs/app-dev.json
# 2. Activa el formato JSON estructurado nativo para el archivo
logging.structured.format.file=logstash
# 3. (Opcional) Si también quieres que la consola de tu IDE muestre JSON
logging.structured.format.console=logstash